name: Update Backend Deployment with ArgoCD
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  build_and_push_backend:
    name: Build and Push backend Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'   

      - name: Build and Push Backend Docker image    
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.BE_REPO_NAME }}
          IMAGE_TAG: ${{ steps.version.outputs.value }}
        run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f backend/Dockerfile .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
            echo "::set-output name=ECR_REGISTRY::$ECR_REGISTRY"
            echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"
          
      - name: Checkout ArgoCD repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: platof/argocd-setup
          ref: main

      - name: Update backend image tag in manifests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.BE_REPO_NAME }}
          IMAGE_TAG: ${{ steps.version.outputs.value }}
        run: |
          sed -i "s|image: .*:[^ ]*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" my-app/backend/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config --global user.email "femmie009@yahoo.com"
          git config --global user.name "platof"
          git add .
          git commit -m "Update Backend Docker image in ArgoCD manifest"
          git push origin main
