name: Collect Directory Names

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Collect Directory Names action
    steps:
      - name: Get directory names
        id: get-directory-names
        uses: actions/collect-directory-names-by-file-glob@v1.1
            
      
      - name: Use Directory Names
        run: echo "Directory Names are ${{ steps.get-directory-names.outputs.directory-names}}
