name: Update Frontend Deployment with ArgoCD
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  build_and_push_frontend:
    name: Build and Push frontend Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
  
      - name: Build and Push Frontend Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.FE_REPO_NAME }}
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f frontend/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=FE_IMAGE::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=ECR_REGISTRY::$ECR_REGISTRY"
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"
  
      - name: Checkout ArgoCD repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: platof/argocd-setup
          ref: main
                  
      - name: Update frontend image tag in manifests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.FE_REPO_NAME }}
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          # Write script to update frontend image tag in YAML manifests
          sed -i "s|image: .*:[^ ]*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" my-app/frontend/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config --global user.email "femmie009@yahoo.com"
          git config --global user.name "platof"
          git add .
          git commit -m "Update Frontend Docker images in ArgoCD manifest"
          git push origin main
        