name: Update Frontend Deployment with ArgoCD
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
permissions:
  contents: write
jobs:
  build_and_push_frontend:
    name: Build and Push frontend Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'   

      - name: Build and Push Frontend Docker image
        id: build_and_push_frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.FE_REPO_NAME }}
          IMAGE_TAG: ${{ steps.version.outputs.value }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f frontend/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "{image}={$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG}" >> $GITHUB_OUTPUT

  update_argocd_manifest:
    name: Update ArgoCD Manifest with New Images
    runs-on: ubuntu-latest
    needs: [build_and_push_frontend]
    steps:
      - name: Checkout ArgoCD repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: platof/argocd-setup
          ref: main

      - name: Debugging - List contents of frontend directory
        run: ls -l my-app/frontend
        
      - name: Debugging - Echo content of deployment.yaml before updating
        run: cat my-app/frontend/deployment.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
                  
      - name: Update frontend image tag in manifests
        env:
          ECR_REGISTRY: ${{ needs.build_and_push_frontend.outputs.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ vars.FE_REPO_NAME }}
          IMAGE_TAG: ${{ needs.build_and_push_frontend.outputs.IMAGE_TAG }}
        run: |
          echo "The image is $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          # Write script to update frontend image tag in YAML manifests
          sed -i "s|image: .*:latest|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" my-app/frontend/deployment.yaml

      - name: Debugging - Echo content of deployment.yaml after updating
        run: cat my-app/frontend/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config --global user.email "femmie009@yahoo.com"
          git config --global user.name "platof"
          git add .
          git commit -m "Update Frontend Docker images in ArgoCD manifest"
          git push origin main
        